"""Emit a self-contained Kaggle training kernel from the ai/ package.

Earlier kernel versions imported ai/ from a companion Kaggle dataset and failed
twice on mount-path differences between workers. Embedding the sources keeps
ai/ as the single source of truth while making the kernel depend on nothing but
the image dataset.

    python scripts/build_kernel.py && kaggle kernels push -p build/kernel
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "build" / "kernel"
AI_FILES = ["__init__.py", "data.py", "model.py", "robustness.py", "explain.py", "train.py"]

HEADER = '''"""E-IDSS training kernel - Kaggle, 2x Tesla T4. GENERATED by scripts/build_kernel.py."""

import glob
import json
import os
import sys
from pathlib import Path

import torch

EMBEDDED_SOURCES = json.loads(r"""__SOURCES__""")

PKG_ROOT = "/kaggle/working/src"
for rel, source in EMBEDDED_SOURCES.items():
    target = Path(PKG_ROOT) / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(source, encoding="utf-8")
sys.path.insert(0, PKG_ROOT)
print("wrote embedded ai package to", PKG_ROOT)

print("=" * 70)
print("GPUs:", torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    props = torch.cuda.get_device_properties(i)
    print(f"  [{i}] {props.name}  {props.total_memory / 1e9:.1f}GB")
print("torch", torch.__version__)
print("=" * 70)

CLASSES = ["crack", "hole", "normal", "rust", "scratch"]
data_root = None
for candidate in sorted(glob.glob("/kaggle/input/*/**/", recursive=True)):
    if all((Path(candidate) / c).is_dir() for c in CLASSES):
        data_root = Path(candidate)
        break
if data_root is None:
    raise SystemExit("data root not found under /kaggle/input")

print("data_root:", data_root)
for c in CLASSES:
    print(f"  {c:<10} {len(list((data_root / c).glob('*.png')))} images")

from ai.train import main  # noqa: E402

sys.argv = [
    "train",
    "--data-root", str(data_root),
    "--arch", "convnext_tiny",
    "--epochs", "20",
    "--batch-size", "64",
    "--workers", "2",
    "--out", "/kaggle/working/models/convnext_tiny_eidss.pt",
]
main()

print("\\nartifacts in /kaggle/working:")
for p in sorted(glob.glob("/kaggle/working/**", recursive=True)):
    if Path(p).is_file() and not p.startswith("/kaggle/working/src"):
        print(f"  {p}  {Path(p).stat().st_size / 1e6:.1f}MB")
'''

METADATA = {
    "id": "sathwikchappala/e-idss-train",
    "title": "E-IDSS Train",
    "code_file": "train_kernel.py",
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": True,
    "accelerator": "nvidiaTeslaT4x2",
    "enable_internet": True,
    "dataset_sources": ["sathwikchappala/eidss-surface-defect"],
    "competition_sources": [],
    "kernel_sources": [],
}


def main():
    sources = {
        f"ai/{name}": (ROOT / "ai" / name).read_text(encoding="utf-8")
        for name in AI_FILES
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    script = HEADER.replace("__SOURCES__", json.dumps(sources))
    (OUT_DIR / "train_kernel.py").write_text(script, encoding="utf-8")
    (OUT_DIR / "kernel-metadata.json").write_text(json.dumps(METADATA, indent=2), encoding="utf-8")
    print(f"built {OUT_DIR / 'train_kernel.py'} embedding {len(sources)} files")


if __name__ == "__main__":
    main()
